---
- hosts: nw8-node5
  vars:
      efsserver: fs-f902d5b2.efs.us-east-1.amazonaws.com
      efsvolume: rhel8-ha
      SID: NW2
      mountopts: vers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport

  tasks:
  - name: mount D32 fs
    import_tasks: 11-instance-fs.yml
    vars:
      num: 32
      efsdir: D{{num}}
      mntdir: /usr/sap/{{SID}}/D{{num}}
