---
- hosts: s4-as-nodes
  tasks:
  - name: create /home/ec2-user/certs dir
    file:
      path: /home/ec2-user/certs
      state: directory
      owner: ec2-user
      group: ec2-user

  - name: create /home/ec2-user/certs/us-east.pem
    copy:
      dest: "/home/ec2-user/certs/us-east.pem"
      owner: ec2-user
      group: ec2-user
      mode: '0400'
      content: |
        -----BEGIN RSA PRIVATE KEY-----
        -----END RSA PRIVATE KEY-----
