---
- hosts: rhel8-hana3
  tasks:
#    - name: Register to RHN and subscribe to a specific pool by ID.
#      redhat_subscription:
#        state: present
#        username: 
#        password: 
#        pool_ids: 

    - name: Enable a RHSM repository
      rhsm_repository:
        name: rhel-8-for-x86_64-baseos-rpms,rhel-8-for-x86_64-sap-solutions-rpms,rhel-8-for-x86_64-highavailability-rpms
