---
- hosts: rhel8-hana3
  vars:
    efsserver: fs-f902d5b2.efs.us-east-1.amazonaws.com
    efsvolume: rhel8-ha
    SID: R81
    mountopts: vers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport 
  tasks:
    - name: /sapmnt Create mountable dir
      file: path=/sapmnt state=directory mode=777 owner=root group=root
    - name: set mountpoints
      mount: name=/sapmnt src={{efsserver}}:/{{efsvolume}}/sapmnt fstype=nfs opts={{mountopts}} dump=0 passno=0 state=mounted
