---
- hosts: rhel8-node1
  vars:
    efsserver: fs-f902d5b2.efs.us-east-1.amazonaws.com
    efsvolume: rhel8-ha
    SID: R81
    efsdir: ERS19
    mountopts: vers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport 
    mntdir: /usr/sap/R81/ERS19
  tasks:
    - name: Create mountable dir
      file: path={{mntdir}} state=directory mode=777 owner=root group=root
    - name: set mountpoints
      mount: name={{mntdir}} src={{efsserver}}:/{{efsvolume}}/{{SID}}/{{efsdir}} fstype=nfs opts={{mountopts}} dump=0 passno=0 state=mounted
    - name: remove fstab entry
      lineinfile: 
        path: /etc/fstab
        state: absent
        regexp: '^{{efsserver}}:/{{efsvolume}}/{{SID}}/{{efsdir}}\s'
