---
- hosts: s4-hana-nodes
  vars:
    hacluster_pwd: pass
    private: yes
    encrypt: "sha512_crypt"
    confirm: yes
    salt_size: 7

  tasks:
  - name: Change Password
    user:
      name: hacluster
      password: "{{ hacluster_pwd | password_hash('sha512') }}"
      update_password: always

- hosts: rhel8-hana1
  tasks:
  - name: Authenticate hacluster
    command: pcs host auth -u hacluster -p pass rhel8-hana1 rhel8-hana2
